/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider */

#ifndef _Included_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
#define _Included_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    CreateNamedPipeNative
 * Signature: (Ljava/lang/String;IIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_CreateNamedPipeNative
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    CreateFileNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_CreateFileNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    ConnectNamedPipeNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_ConnectNamedPipeNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    DisconnectNamedPipe
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_DisconnectNamedPipe
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    readNative
 * Signature: (JJ[BIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_readNative
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint, jboolean);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    writeNative
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_writeNative
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    CloseHandleNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_CloseHandleNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    GetOverlappedResultNative
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_GetOverlappedResultNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    CancelIoEx
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_CancelIoEx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    CreateEventNative
 * Signature: (ZZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_CreateEventNative
  (JNIEnv *, jobject, jboolean, jboolean, jstring);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    WaitForSingleObjectNative
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_WaitForSingleObjectNative
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_GetLastError
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    NewOverlappedNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_NewOverlappedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    DeleteOverlappedNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_DeleteOverlappedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    getErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_getErrorMessage
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    ERROR_IO_PENDING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_ERROR_1IO_1PENDING
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    ERROR_NO_DATA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_ERROR_1NO_1DATA
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    ERROR_PIPE_CONNECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_ERROR_1PIPE_1CONNECTED
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    FILE_ALL_ACCESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_FILE_1ALL_1ACCESS
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    FILE_FLAG_FIRST_PIPE_INSTANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_FILE_1FLAG_1FIRST_1PIPE_1INSTANCE
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    FILE_FLAG_OVERLAPPED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_FILE_1FLAG_1OVERLAPPED
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    FILE_GENERIC_READ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_FILE_1GENERIC_1READ
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    GENERIC_READ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_GENERIC_1READ
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    GENERIC_WRITE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_GENERIC_1WRITE
  (JNIEnv *, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider
 * Method:    PIPE_ACCESS_DUPLEX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIWin32NamedPipeLibraryProvider_PIPE_1ACCESS_1DUPLEX
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
