/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider */

#ifndef _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
#define _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    socketNative
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_socketNative
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    bindNative
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_bindNative
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    listenNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_listenNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    acceptNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_acceptNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    connectNative
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_connectNative
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    readNative
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_readNative
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    writeNative
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_writeNative
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    closeNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_closeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    shutdownNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_shutdownNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    errString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_errString
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
