/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scalasbt_ipcsocket_UnixDomainSocketLibrary */

#ifndef _Included_org_scalasbt_ipcsocket_UnixDomainSocketLibrary
#define _Included_org_scalasbt_ipcsocket_UnixDomainSocketLibrary
#ifdef __cplusplus
extern "C" {
#endif
#undef org_scalasbt_ipcsocket_UnixDomainSocketLibrary_PF_LOCAL
#define org_scalasbt_ipcsocket_UnixDomainSocketLibrary_PF_LOCAL 1L
#undef org_scalasbt_ipcsocket_UnixDomainSocketLibrary_AF_LOCAL
#define org_scalasbt_ipcsocket_UnixDomainSocketLibrary_AF_LOCAL 1L
#undef org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SOCK_STREAM
#define org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SOCK_STREAM 1L
#undef org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SHUT_RD
#define org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SHUT_RD 0L
#undef org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SHUT_WR
#define org_scalasbt_ipcsocket_UnixDomainSocketLibrary_SHUT_WR 1L
/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_socket
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    bind
 * Signature: (ILorg/scalasbt/ipcsocket/UnixDomainSocketLibrary/SockaddrUn;I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_bind
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_listen
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    accept
 * Signature: (ILorg/scalasbt/ipcsocket/UnixDomainSocketLibrary/SockaddrUn;Lcom/sun/jna/ptr/IntByReference;)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_accept
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    connect
 * Signature: (ILorg/scalasbt/ipcsocket/UnixDomainSocketLibrary/SockaddrUn;I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_connect
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    read
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_read
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_write
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_scalasbt_ipcsocket_UnixDomainSocketLibrary
 * Method:    shutdown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_UnixDomainSocketLibrary_shutdown
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
